### ISSUE TITLE
Data Elements Glossary

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1000]
As a Bidder
I want to be informed about the definition of terms used in TalentMAP
so that I understand the information while I am searching for positions

## Acceptance Criteria
* Provide a glossary of TalentMAP terms and data fields
* Provide a mechanism for users to call upon the glossary

## Findings
User do not understand data elements

## Recommendation
Tooltip UI to provide users information on new data sets

## User Research
The team will continue to do research. 

## Resources
We are collecting terms to define in our [Styleguide](https://github.com/18F/State-TalentMAP/wiki/Content-styleguide#specific-words-and-phrases)

**Comment by wongperson** [comment]
@krisdelacruz please add a story dependency for UX tasks against this epic

**Comment by mjoyce91** [comment]
Slated for brainstorming on 12/12/17.

**Comment by jseppi** [comment]
Here's the 18F glossary package: https://github.com/18F/glossary

**Comment by burgwyn** [comment]
I was thinking "COTS" so this looks promising

**Comment by krisdelacruz** [comment]
Ideation Session

<img width="1283" alt="screen shot 2017-12-12 at 4 05 43 pm" src="https://user-images.githubusercontent.com/16211502/33911102-2f94506e-df5f-11e7-9c6b-3a62a3b9cd7e.png">
<img width="1012" alt="screen shot 2017-12-12 at 4 06 03 pm" src="https://user-images.githubusercontent.com/16211502/33911103-2fb651aa-df5f-11e7-81d6-52059f258c7b.png">

**Comment by krisdelacruz** [comment]
**Note:** There is an OBC existing bidding terms glossary. Is it possible to pull that and use it as our foundation/base for this Glossary? 

We might need to do an content audit to make sure if its "Post" related glossary or "Department of State Bidding" related glossary.

**Comment by wongperson** [comment]
OBC glossary could not be found, per @rutherfordrk

**Comment by mjoyce91** [comment]
@jseppi I like the 18F glossary package, however it will need to be "react-ified". I think it provides a good starting point for CSS and structure on building one ourselves.
