### ISSUE TITLE
Handshake visualization

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1001]
As a Bidder
I want a visualization if the position received a handshake
so that I can search for positions efficiently

## Findings
Capsule descriptions should help people skim through positions

## Recommendation
Provide Bidders the most needed data

## User Research
The team will continue to do research. Phase 2 will reflect this action

**Comment by wongperson** [comment]
Closing as this feature already exists in backlog/to-do for development.
