### ISSUE TITLE
Authenticate against a SAML2 endpoint

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#1003]
As a user,
I want the system to verify that I am who I say I am,
So that I can use the system with respect to my permissions

## Acceptance Criteria
* Take user input and send to mock SAML2 endpoint
* No integration with PIV
* Authenticate against a non-production endpoint within the Dept. of State

**Comment by jseppi** [comment]
@burgwyn: still planning to make this a spike, or will you try to integrate directly (probably with the API)?

**Comment by afrasier** [comment]
I've been poking around hunting for a SAML2/ADFS library for Django and these are the following I've found, I'm no ADFS/SAML2 expert so input is appreciated:

[django_auth_adfs](http://django-auth-adfs.readthedocs.io/en/latest/index.html)
[django-saml-service-provider](https://github.com/KristianOellegaard/django-saml-service-provider) - This uses python-saml, not sure how intrinsically tied in that is to the OneLogin service
[python-saml-adfs](https://github.com/Trondheim-kommune/python-saml-adfs)

@burgwyn @jseppi @jesse-russell

**Comment by afrasier** [comment]
Looking at [python-saml](https://github.com/onelogin/python-saml) is probably the best choice - it's the most mature. Requires a little extra elbow grease from me but it is a bit more flexible.

**Comment by jseppi** [comment]
I asked in our #python and #django channels to see if anyone has any experience with any of those libraries. Will update with any comments/advice from folks.

**Comment by jseppi** [comment]
Some comments about `python-saml`:

> It worked OK, but isn't super well written. If you look under the hood it's clearly a straight port of their PHP library.

> That not far from my take in #django. I haven't used it, but just looking at their docs, Django appears to be an afterthought.
 
> It shows up especially in the error handling, where you have to call get_last_error like methods instead of having exceptions raised.

**Comment by afrasier** [comment]
Hmm, any opinions on where to go from here then?

**Comment by jseppi** [comment]
Got one recommendation for https://github.com/knaperek/djangosaml2

**Comment by afrasier** [comment]
I like that one, looks like it jives well with Django + supports regular auth (good for demos) and SAML.

**Comment by afrasier** [comment]
This issue is now done/obsolete with implementation of ADFS in DOS architecture.
