### ISSUE TITLE
Contact Details on Post

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1006]
As a Bidder
I need contact details directly on the posts
so that I can reach out to the contact to gather more information

## Findings
Capsule descriptions should help people skim through positions

## Recommendation
Provide Bidders the most needed data

**Comment by wongperson** [comment]
Bidders contact both post officials, bureau, and position incumbents.

**Comment by wongperson** [comment]
Closing as it is a duplicate for a feature that is already implemented.  Edwin to update with feature # duplication.
