### ISSUE TITLE
Bidder Notifies CDO for System Challenges

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1011]
As a Bidder
I want to notify my CDO if I am not able to search for positions on TalentMAP because of performance issues
so that s/he is aware

## Acceptance Criteria
* CDO is notified on the CDO Dashboard or email
* CDO Dashboard depicts Bidders with TalentMAP challenges

## Findings
Capsule descriptions should help people skim through positions

## Recommendation
Provide Bidders the most needed data

## User Research
The team will continue to do research.

**Comment by wongperson** [comment]
Closing to open a new story of Bureau-level listing of handshake.
