### ISSUE TITLE
Homepage Map Interaction - Iteration

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1012]
As a Bidder
I want to dig deeper on the map (skill code, grade, post, etc) 
so that I can search for positions efficiently

## Acceptance Criteria
* Recommendation: Add Skill Code drop down
* Recommendation: Add Grade Dropdown

## User Research
The team will continue to do research.

**Comment by esgoodman** [comment]
Closing -- [approved wireframes](https://projects.invisionapp.com/share/SQFA0SE5B#/screens/272828266) don't have the map.
