### ISSUE TITLE
Minor Edits- Search Bar Interaction 

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1055]
The interaction to collapse and open the search bar. Similar to USAjobs search feature.

If not we can completely take away "Search" on the Primary Navigation and have it accessible globally. 

http://g.recordit.co/haGyYmBYiC.gif

**Comment by krisdelacruz** [comment]
Screenshot from Mocks. Utilizing #00293F to highlight "Search"

<img width="1273" alt="screen shot 2017-12-04 at 12 22 16 pm" src="https://user-images.githubusercontent.com/16211502/33566577-6737dd32-d8ee-11e7-9f2d-3565e70f1870.png">

**Comment by mjoyce91** [comment]
Need to move search bar into the header as a connected component and toggle its visibility in state with the Search link.
