### ISSUE TITLE
Content Edit - Bureau Data set

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1090]
As a bidder
I want to see Bureau information with abbreviation (i.e. **(AF) BUREAU OF AFRICAN AFFAIRS** )
so that I can quickly search through bureaus

## Acceptance Criteria
- Homepage Dropdown
- Search Results Page
- Bidder Profile
- CDO Portfolio View

## Bureaus

- (WHA) BUREAU OF WESTERN HEMISPHERIC AFFAIRS 
- (EUR) BUR OF EUROPEAN AFF AND EURASIAN AFFAIRS (EUR)
- (EAP) BUREAU EAST ASIAN AND PACIFIC AFFAIRS 
-  (NEA) BUREAU NEAR EASTERN AFFAIRS 
- (SCA) BUREAU OF SOUTH AND CENTRAL ASIAN AFFAIRS 
- (AF) BUREAU OF AFRICAN AFFAIRS (AF)
- (IO) BUREAU OF INTERNATIONAL ORG. AFFAIRS

**Comment by esgoodman** [comment]
@afrasier @mjoyce91 Can we close this? Looks like it's done.

**Comment by esgoodman** [comment]
It is done!
