### ISSUE TITLE
Account Dropdown does not fully render in Microsoft Edge

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#1096]
Using Microsoft Edge, the Account Dropdown does not render on click. It only renders on pressing the enter key. However, the correct class is applied in either case, and once another spot on the screen is clicked, the Account Dropdown appears briefly.

Windows 10
Edge 41.16299.15.0

![dec-07-2017 13-03-52](https://user-images.githubusercontent.com/11576347/33730820-2a18b986-db4f-11e7-92cf-8efc9de01737.gif)

**Comment by jseppi** [comment]
😬

**Comment by mjoyce91** [comment]
To get around this issue, we can use react-simple-dropdown's [removeElement](https://github.com/Fauntleroy/react-simple-dropdown#options) prop to create and destroy the element from the DOM on click.

**Comment by mjoyce91** [comment]
For some reason including this prop is not destroying and recreating the element anymore. It's also throwing console warnings because the `removeElement` attribute is being applied to a `div` and `removeElement` is not a valid attribute.

**Comment by jseppi** [comment]
Maybe our `yarn.lock` has an incorrect version or something?

**Comment by mjoyce91** [comment]
Somewhere along the way, our version got out of whack. Newer version includes the `removeElement` feature. Updating resolves both issues.
