### ISSUE TITLE
UI - Create Tooltip/Carret Window for In-Panel Bid status

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#1119]

**Comment by mjoyce91** [comment]
Trying to get this merged into the rc-steps component https://github.com/react-component/steps/pull/42

**Comment by mjoyce91** [comment]
https://github.com/react-component/steps/pull/42 merged! @burgwyn @jseppi

**Comment by jseppi** [comment]
@mjoyce91 Nice!
