### ISSUE TITLE
Interview Single Bidders

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#113]
As a user researcher,
I want to better understand single bidders,
so that the team gains baseline understanding of experience and needs and goals.

Acceptance Criteria

- Recruiting candidates
  - Capture participants at a variety of career levels
- Interview 4 to 5 bidders

 Definition of Done

- Interviews completed
- Executive summary of finding posted to wiki

Optional

- Attendance by a developer and/or a member of Department of State

**Comment by krisdelacruz** [comment]
List of users being compiled: 
 Bidding with disabilities (if self-identified)
·         Bidding single
·         Bidding married (tandem)
·         Bidding with children
·         Bidding married with children
·         Bid-Pro Participants
·         Entry level Bidders (even if they are directed its still good to get their story)
·         Single Female Mid-Level Bidder
·         Single Female Senior-Level Bidder
·         Single Male Mid-Level Bidder
·         Single Male or female that is currently working overseas (Does Robert Barney fit this description?).
