### ISSUE TITLE
UI - Implement position card redesign

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#1162]

**Comment by esgoodman** [comment]
@mjoyce91 Is this a UX redesign story or a dev story?

**Comment by mjoyce91** [comment]
Dev. I've been using the prefix "UI" for my subtasks of epics. Maybe I could use "UI Dev" to keep it clear?

**Comment by krisdelacruz** [comment]
@esgoodman This is dev. But since we have received feedback there might be a small iteration on this. @Mike let’s hold a sec for homepages until I review feedback from 18f designers
