### ISSUE TITLE
UI - Implement overall homepage redesign

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#1168]
As a TalentMAP Front-End Developer,
I want to develop the redesigned homepage
So that the prototype reflects the approved designs

### More details
- The overall structure of the homepage has been approved. 
- Final resolution of the issue depends on #1206 (but #1206 is not a blocker for starting this!) 

### Acceptance criteria
Sign-off from @krisdelacruz, @esgoodman, or @wongperson 

### Resources
Approved [homepage comp](https://projects.invisionapp.com/share/SQFA0SE5B#/screens/272828266)

![homepage-update comp](https://user-images.githubusercontent.com/10067318/35055669-94732778-fb64-11e7-966e-fdb1d0f0ec72.png)

**Comment by burgwyn** [comment]
Closing
