### ISSUE TITLE
UI - Integrate with glossary library

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#1187]

**Comment by esgoodman** [comment]
You can pull an initial set of items for the glossary from the [Styleguide list](https://github.com/18F/State-TalentMAP/wiki/Content-styleguide) in the wiki. Caveat: these definitions have not been vetted by SMEs and so are liable to change. 

@apbdevine - we will need to set up time with Robin to review content in any PR before it is released.

**Comment by burgwyn** [comment]
@esgoodman - I agree.  I wonder if we add 2 additional issues.  We have the tasks to develop the glossary, but perhaps we create an issue to review the items with Robin and then a second issue to load the approved set?

**Comment by esgoodman** [comment]
@burgwyn I have created them and added them to the epic.

**Comment by burgwyn** [comment]
@esgoodman - awesome, thanks!
