### ISSUE TITLE
UI - Load approved glossary content

### ISSUE THREAD

**Issue by esgoodman** [18F/State-TalentMAP#1194]
As a usability tester for TalentMAP, 
I need accurate glossary content,
So that I have a more valid testing experience

## Acceptance criteria
Approved content from SME moved into data elements storage for glossary component

**Comment by mjoyce91** [comment]
Added `Back End Dev` label since this loading will likely be on the API @afrasier

**Comment by afrasier** [comment]
Yup, will just need a csv to load.

**Comment by burgwyn** [comment]
Closing
