### ISSUE TITLE
User story template

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#12]
** User Story **
As a <user type>,
I want to <task>,
so that <goal>

** Acceptance Criteria **

** Definition of Done **

**Comment by apbdevine** [comment]
Reviewed with team during Grooming Session on 6/7

**Comment by bradnunnally** [comment]
I'm attempting to create a standard Issue Template which can be used going forward when creating new issues. https://github.com/18F/State-TalentMAP/blob/issue-template/.github/ISSUE_TEMPLATE.md

@wongperson had some feedback that I still need to touch base on and incorporate, but wanted to get this out there for others to see too.

**Comment by burgwyn** [comment]
Closed as this is complete
