### ISSUE TITLE
View Post Profile - Mission Data

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#122]
As a bidding employee,
I would like view a post profile's mission data
So I can research on a post

**Acceptance Criteria**

* Display specific post mission data
  * Country
  * City
  * Type of post - eg, embassy, consulate
  * Inter and intra agency representation
    * Points of Contact
  * Language(s)
  * R & R alignment
  * Danger pay
  * Post differential pay
  * Service needs differential
  * COLA
  * Consumables

**Comment by mjoyce91** [comment]
Currently using placeholder data for **type** (hard coded in HTML as "Embassy") and **Inter and intra agency representation - Points of Contact** (hard coded in HTML as "John Doe") on Post profiles.
