### ISSUE TITLE
Code splitting for front end JavaScript bundle.

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP#1272]
The front end JavaScript bundle is pretty large, currently weight in at ~1.3MB. I think we're going to want to implement code splitting, probably by route, to speed up initial loads.

**Comment by mjoyce91** [comment]
Here's an approach that looks promising - https://serverless-stack.com/chapters/code-splitting-in-create-react-app.html

**Comment by burgwyn** [comment]
I'd propose splitting this into 2 tasks:

1. Split app and vendor bundles
2. Create route bundles

**Comment by jseppi** [comment]
hrm, I'm not totally sure splitting the app and vendor bundles will get us to where we want, but it's worth a try. I don't have much experience with the latest and greatest bundle chunking, so please let me know if I'm off-base here :)

The reason I think it won't quite work as well as a single bundle split by route is because assumedly we'd need the _entire_ vendor bundle loaded at app load if we split that way, regardless of the chunking of the app bundle.

If we _just_ do a single bundle (vendor and app), split by route, the chunks would include only the vendor _and_ app chunks we need for the targeted route, resulting in a smaller request size overall.

That probably doesn't read very clearly, so maybe this contrived example breakdown will help explain what I mean:

Assuming:
- all vendor assets: 500kb
- all app assets: 500kb

Using two bundles, no splitting:
- Total load: 1000kb

Using two bundles, but splitting the app by route, and visiting route `/example`:
- all vendor assets are loaded: 500kb
- just the `/example` route chunk of app is loaded: 100kb
- Total load: 600kb

Using single bundle, with the whole thing split by route, and visiting route `/example`:
- Just the `/example` route chunk of app assets _and_ vendor assets are loaded: 400kb (300 from the necessary vendor code, and 100 from the app chunk)
- Total load `400kb`

**Comment by mjoyce91** [comment]
This looks pretty cool - https://github.com/thejameskyle/react-loadable

And this section looks fun - https://github.com/thejameskyle/react-loadable#preloading

**Comment by mjoyce91** [comment]
I think we could achieve the same goal by performing rendering at a component level instead of a route level and get even more optimizations. From a UX perspective, it also gives you more fine-tuned controls over displaying loading visualizations.

**Comment by jseppi** [comment]
Whoooaaa, I had not seen `react-loadable` before. That looks very promising!

**Comment by mjoyce91** [comment]
Here's some examples of how we could use it - https://github.com/18F/State-TalentMAP/pull/1299

**Comment by mjoyce91** [comment]
Helpful in visualizing file size for components and dependencies - https://chrisbateman.github.io/webpack-visualizer/

draft-js is 20% of our bundle size 😮

**Comment by jseppi** [comment]
Wow o_O

I really like that visualizer. I added as an npm script command on another project and check it periodically to make sure deps are looking good.

**Comment by burgwyn** [comment]
Closing
