### ISSUE TITLE
Content: Clarify label for Tour End Date

### ISSUE THREAD

**Issue by esgoodman** [18F/State-TalentMAP#1285]
As a bidder using TalentMAP,
I need to understand what the month/date shown for "Tour End Date" means
So that I don't get confused about whether a position is realistically workable for me.

### Currently
We don't have this implemented, but we have done research that suggests we need Tour End Date in the position description. We are currently working on it - see #1002.

However, "Tour End Date" is ambiguous -- is it the incumbent's end date? The successor's end date? The State Department has tours of varying lengths, so correct referent might be unclear. 

### Acceptance criteria
Team agrees on any changes

### Research findings
We know that Tour End Date is an important criterion when bidders evaluate likely positions. See #1002 for more. We do not have research yet on the clarity (or lack thereof) of our UI label.

**Comment by krisdelacruz** [comment]
@jamiealbrecht @esgoodman 

This was an email from the clients:

"TalentMAP Team,

The acronym TED = Tour End Date, or most commonly know as the Transfer Eligibility Date.  Sometimes it’s also referred to as the Time of Estimated Departure.  For TalentMAP purposes we should use **Transfer Eligibility Date**

 

The Transfer Eligibility Date (TED, or sometimes Estimated Time of Departure) is the date of arrival at their assignment, plus their tour length. (Generally 12, 24, or 36 months.) Positions are advertised on the Summer or Winter bid lists based on their TED.

The Transfer Eligibility Date may vary depending on:

·         Curtailments
·         Assignment Extensions
·         Needs of the Services"

**Comment by jamiealbrecht** [comment]
I have a few questions and I apologize if they've been answered already:

Is it most commonly known as "Transfer Eligibility Date" to applicants? What do they do with this date and how does it play into their search process? Also, just to clarify, there are four ways of referring to the exact same date?

- Tour end date 
- Time of estimated departure 
- Estimated time of departure 
- Transfer eligibility date 

Have we tested and or asked applicants about each of these options?

**Comment by esgoodman** [comment]
Decision! We will go with 'transfer eligibility date' for now, but ask about in #1288.

**Comment by burgwyn** [comment]
Removing from epic #256
