### ISSUE TITLE
Usability test position research features

### ISSUE THREAD

**Issue by esgoodman** [18F/State-TalentMAP#1288]
As a TalentMAP teammember,
I need to validate that bidders are able to narrow down their choices and that it's **valuable** narrowing
So that we can go live with confidence in the functionality

### Currently
Our current homepage and search results page draws on a round of usability testing and a next round of paper prototyping. We are implementing those features, but need to test them to make sure they help bidders quickly create a shortlist. 

### Goal
Test usability and comprehension of our information architecture, content labelling, interaction design.

### Steps
- Determine schedule and participants for FSI
- Setup booth/kiosk @ FSI
- Refine hallway usability testing procedures #1377 
-- Develop exercises for testing to hit readability & legibility points (highlighter exercise!)
- Develop paper prototype OR script flow for dev site

### Acceptance criteria
Test report and any recommendations for changes

**Comment by wongperson** [comment]
I believe this task is already completed (and a duplicate) under #980.  Seeking to close.

**Comment by cydneycappello** [comment]
This task is complete. Closing now!
