### ISSUE TITLE
Document QASP Requirements - Tested Code - Backend

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#13]
As a GSA TTS product manager, I need a documented strategy for addressing Quality Assurance Surveillance Plan action items, so that I can measure product quality.

Acceptance criteria:

* Follow guidance outlined on the original [QASP document](https://github.com/18F/bpa-DOS-TalentMAP/blob/master/Attachment3_PWS-QASP.md)
* Document a strategy to maintain quality targets
* Publish findings to [the wiki](https://github.com/18F/State-TalentMAP/wiki)

**Comment by afrasier** [comment]
This is completed by 

https://github.com/18F/State-TalentMAP/wiki/QASP/b370506f9abc73de6a19f918b279861ae60e9848

I'll leave this open for now so we can give Zenhub a shot.
