### ISSUE TITLE
Fix "method_complexity" issue in src/Components/ProfileDashboard/PositionInformation/PositionInformation.jsx

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP#1310]
Function `PositionInformation` has a Cognitive Complexity of 13 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/18F/State-TalentMAP/src/Components/ProfileDashboard/PositionInformation/PositionInformation.jsx#issue_5a6f3a902b12380001000443

**Comment by mjoyce91** [comment]
Duplicate of https://github.com/18F/State-TalentMAP/issues/1366
