### ISSUE TITLE
Fix "complex_logic" issue in src/Containers/Results/Results.jsx

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP#1317]
Consider simplifying this complex logical expression.

https://codeclimate.com/github/18F/State-TalentMAP/src/Containers/Results/Results.jsx#issue_5a6f3a8c2b1238000100043b

**Comment by mjoyce91** [comment]
Resolved via https://github.com/18F/State-TalentMAP/pull/1334
