### ISSUE TITLE
Incorporate library for nested traversal

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#1345]
Look into https://www.npmjs.com/package/dot-prop and use instead of conditionally checking for nested properties.

**Comment by jseppi** [comment]
@afrasier wrote himself a similar helper for the api code: https://github.com/18F/State-TalentMAP-API/blob/dev/talentmap_api/common/common_helpers.py#L32

**Comment by jseppi** [comment]
also it might be nice to encapsulate some default value behavior into a wrapping method:

```js
function propOrDefault(obj, path, default = null) {
  return dotProp.get(obj, path) || default;
}

//...

// in a component somewhere...
const ccc = propOrDefault(position, 'aaa.bbb.ccc', NO_CCC);
