### ISSUE TITLE
Release Candidate - Prototype Message

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#1435]
As a product owner,
I want to display a message to users that this application is under active development,
So that users are aware of future changes

## Acceptance Criteria
- A brief message indicating the development status of the application to place in the "this is a government site" bar, much like the one that @RyanSibley wrote for FOIA.

**Comment by esgoodman** [comment]
Assigning to @RyanSibley as a starter task to help her get acquainted with the project.

**Comment by RyanSibley** [comment]
This was message I intended for FOIA.gov: 

<img width="434" alt="screen shot 2018-02-14 at 2 50 40 pm" src="https://user-images.githubusercontent.com/1151139/37044479-8f785b2e-2131-11e8-93d5-26f68c79e8f2.png">

If we want something short, and we are collecting feedback, we could say: 

`Welcome to TalentMap! This site is new and will continue to be improved based on your feedback. <link>Please let us know what you think!</link>`

^^The phrasing implies beta, but emphasizes a focus on improvement and feedback.

**Comment by RyanSibley** [comment]
After talking to Edwin, something like this might be more appropriate:

`Welcome to TalentMap! This site is new and features will continue to be added. <link>Read more about how to use this site and what's to come. </link>`

What can be found in the `read more` link should be covered by what #1503 is sorting out.

**Comment by krisdelacruz** [comment]
@RyanSibley Thank you! Will mock up for RC

**Comment by burgwyn** [comment]
Closing
![disclaimer](https://user-images.githubusercontent.com/661204/37532340-24afc458-2915-11e8-8d92-5f6c6a2a3430.png)

**Comment by RyanSibley** [comment]
After some back and forth, I've updated what them message should say: 

`Welcome to TalentMap!  Use this site to research positions and continue to <link>bid using FSBid.</link> New features <link>coming soon.<link/>`

The `coming soon` link will go the about page.  cc @wongperson
