### ISSUE TITLE
UI Dev - Use a custom id for row keys in the HomepagePositionsList component

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#1469]
Because we use `shortid` for the rows here, the `key`s are regenerated after toggling the favorites button, resulting in the button losing focus between clicks. Make use a of a custom title along with the row number to ensure that rows have the same `key`s between renders. Ex: `'service-need-row-1'`, `'service-need-row-2'`, `'recently-posted-row-1'`, etc.

**Comment by mjoyce91** [comment]
@jseppi - this is related to the discussion we had on your PR feedback, and would ensure uniqueness for the rows.

**Comment by burgwyn** [comment]
Closing
