### ISSUE TITLE
Home Page - Skill Code Filter

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#1473]
Skill Code filter is illegible

IE11
![image](https://user-images.githubusercontent.com/661204/36597473-399490be-1877-11e8-8a34-a01c1206c639.png)

Chrome
![image](https://user-images.githubusercontent.com/661204/36597453-260825d8-1877-11e8-9f14-4551cc5cc018.png)

**Comment by mjoyce91** [comment]
Resolved in https://github.com/18F/State-TalentMAP/pull/1477
