### ISSUE TITLE
User Feedback Mechanism

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#1474]
As a user,
I would like a mechanism to provide feedback,
So that I can share my feelings and experiences with the product team

## Acceptance Criteria
* A short survey with questions
* A design for the interface

## Notes
Consider fec.gov as an example
![image](https://user-images.githubusercontent.com/661204/36598169-44d5697e-1879-11e8-96ab-5d895f4f19d7.png)

Alternately, Microsoft (we wouldn't tweet)
<img width="475" alt="screen shot 2018-02-23 at 2 32 51 pm" src="https://user-images.githubusercontent.com/661204/36613121-8e3d53e2-18a6-11e8-9cc2-11cd411aff4d.png">

**Comment by mjoyce91** [comment]
Do we want to turn this into an epic? I can add some subtasks and possibly get something started for this Kanban.
