### ISSUE TITLE
API - SOAP Pagination

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#1520]
Paging in SOAP requests is is not adding 1 to start index.  Example output:

100
199
298
397

Meaning each page has one duplicate entry - `Got: 99 new, 1 updated`

**Comment by afrasier** [comment]
This, I believe, is necessary, because the next start index is not guaranteed to be `n+1`, since the indexes are actually id's.

**Comment by afrasier** [comment]
I think the best fix would be to have the SOAP response return the "start of next page" instead of the last id.

**Comment by patduggan** [comment]
The SOAP response now includes the paginationStartKey in the response. It is a row count rather than a last id. You should be able to take last + 1. Let me know if this does not work

**Comment by afrasier** [comment]
Ah great! Thanks for the clarification. I'll update accordingly.

**Comment by burgwyn** [comment]
Closing
