### ISSUE TITLE
UI - Map AccountDropdown to 'DisplayName'

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#1526]
Currently, the account dropdown is mapped to the logged in user's first name.  There were previous versions where the field was mapped to the user's username.

<img width="206" alt="screen shot 2018-03-05 at 9 28 01 am" src="https://user-images.githubusercontent.com/661204/36980191-9c16bcfc-2057-11e8-93aa-9f11d3f6ef15.png">

Recommend creating a generic `display_name` field to handle the uncertainty of what field(s) will be available in future environments.

**Comment by mjoyce91** [comment]
Would this be an API task?

**Comment by burgwyn** [comment]
Closing
