### ISSUE TITLE
Feedback mechanism mock up

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#1531]
As a TalentMAP Designer
I will create a mockup of the Feedback mechanism
So that users are able to provide feedback for RC release

**Comment by krisdelacruz** [comment]
Brainstorming session with @mjoyce91 

<img width="1105" alt="screen shot 2018-03-06 at 2 44 36 pm" src="https://user-images.githubusercontent.com/16211502/37054459-ec12cc3c-214c-11e8-8e65-c77b4a421a66.png">

**Comment by cydneycappello** [comment]
This is in development, marking as done.
