### ISSUE TITLE
Fix "method_complexity" issue in src/Components/FeedbackForm/FeedbackForm.jsx

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP#1588]
Function `FeedbackFormComponent` has a Cognitive Complexity of 6 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/18F/State-TalentMAP/src/Components/FeedbackForm/FeedbackForm.jsx#issue_5aa7eb36bb3fcb00010004c3

**Comment by burgwyn** [comment]
CLosed in #1590
