### ISSUE TITLE
Chrome - Skill Code Search

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#1664]
![image](https://user-images.githubusercontent.com/661204/37840921-b6864756-2e94-11e8-983e-6000531fd1ec.png)

![image](https://user-images.githubusercontent.com/661204/37840963-d320a352-2e94-11e8-9485-a198c173fa72.png)

**Comment by Icemanbeta** [comment]
a7b434b346a55cabe76109f3f6e888192ed64736
