### ISSUE TITLE
Language Long Names Presentation

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#1759]
***Expected Behavior***
Language names are written as their full language names instead of the given abbreviated names from the source data.

***Prerequisites***
1) Full dump of languages retrieved by API
2) Return a list of preferred language names and dialects (DoS @BrownCA5 @rutherfordrk)
3) Apply preferred language names and dialects

***Assumptions***
Existing languages as provided from SOAP services is already grouped by language first with dialect suffix.

**Comment by wongperson** [comment]
@afrasier @mjoyce91 please estimate for consideration.

**Comment by afrasier** [comment]
Backend is roughly 3 points to add a new display name column + load the CSV.
I have e-mailed Chris and Robin a CSV of the current list of languages and their long/short descriptions.

**Comment by mjoyce91** [comment]
If this was handled on the API, I would just need to update the field we're using (1 point).

If we're handling this mapping on the front-end instead of the back-end, 5 points to map a pre-defined list against languages currently in the API.

**Comment by afrasier** [comment]
This has been resolved and deployed in DoS environment.
