### ISSUE TITLE
Update spacing on Tour of Duty content

### ISSUE THREAD

**Issue by cydneycappello** [18F/State-TalentMAP#1781]
### Current
2 YRS (3R&R) has different spacing compared to other Tour of Duty options, like 1 YR (3 R & R)

### Desired
Make 2 YRS (3R&R) to appear as 2 YRS (3 R & R).

**Comment by burgwyn** [comment]
A webservices update was made.  Awaiting on-site confirmation.

**Comment by afrasier** [comment]
This has been resolved.

![image](https://user-images.githubusercontent.com/6662582/39760117-89f7446a-52a2-11e8-9f39-1b7b5d9ea103.png)
