### ISSUE TITLE
Apply design to post detail view

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#186]
As a bidder,
I want a clear visual design of the post detail view
So that I can visualize the details of a post in a logical and intuitive manner

## Acceptance criteria
- A wireframe representation of the post details view
- Applies the design created by the design team
- Applies the US Web Design Standards

### Resources
- State Department style guide

**Comment by esgoodman** [comment]
Closing -- we will be providing links to the [Overseas Briefing Center] (https://www.state.gov/m/fsi/tc/c6954.htm) instead of creating our own post details page.
