### ISSUE TITLE
Defect - Posted Date Discrepancies

### ISSUE THREAD

**Issue by LisaReddy** [18F/State-TalentMAP#1869]
<Posted Date Discrepancies

### Steps
- [1 ] Go to Search page
- [2 ] Filter on 2018 DCM/PO Cycle bidding cycle using Left panel search
- [3 ] The result set shows 00000042 with posted date of 6/1/2017
- [4 ] FSBID reult set shows 00000042  with posted date of 6/2/2017

### Acceptance criteria
The system should retrieve the correct Posted date 

### User Story
As a bidder, I need to see the correct posted date for a position I search

 screenshots:
-
![posted_date_discrepancy](https://user-images.githubusercontent.com/37226508/39590105-74ff5144-4eef-11e8-8652-63ccf2362178.jpg)
![tm_posted_date](https://user-images.githubusercontent.com/37226508/39590134-8b351340-4eef-11e8-853a-a23f626b970c.jpg)

**Comment by wongperson** [comment]
Theory that the date/time is being interpreted by TalentMAP in a different timezone compared to FSBID.  @burgwyn and @afrasier to investigate what timezone FSBID uses.

**Comment by LisaReddy** [comment]
Corrected with new build
Closing issue
