### ISSUE TITLE
Apply design to home page view

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#187]
As a bidder,
I want a clear visual design of the home page view
So that I can visualize the home page in a logical and intuitive manner

## Acceptance criteria
- A wireframe representation of the position search view
- Applies the design created by the design team
- Applies the US Web Design Standards

### Resources
- State Department style guide

**Comment by burgwyn** [comment]
Need further discussion with @krisdelacruz

**Comment by krisdelacruz** [comment]
Created two home page mock ups. Going through internal feedback and will send over for approval on which direction the team will go towards. 

This also factors in the Style Tiles that was chosen. At this time "Style Tile 1" with the U.S. Web Standards stylistic approach is up in the running.
