### ISSUE TITLE
Defect - Language dropdown list

### ISSUE THREAD

**Issue by LisaReddy** [18F/State-TalentMAP#1878]
<Language dropdown list displays Null values on the left search panel

Probably due to data syncing issues.

![language-dropdown](https://user-images.githubusercontent.com/37226508/39636137-e4dcf452-4fae-11e8-9597-6e8b868c3bb8.jpg)

**Comment by burgwyn** [comment]
@mjoyce91 do we use `formal_description`?

**Comment by mjoyce91** [comment]
@burgwyn Yes

**Comment by mjoyce91** [comment]
Did it get changed to something else?

**Comment by burgwyn** [comment]
No, just re-running `update_string_representations` on the API

**Comment by LisaReddy** [comment]
The Language list is being displayed but field value is also displayed.
![language_field_value](https://user-images.githubusercontent.com/37226508/39702246-a6e2bd98-51f3-11e8-988c-3bcd2e3385ec.jpg)

**Comment by burgwyn** [comment]
@LisaReddy - are you referring to the "(AB)" in "Albanian (AB)"?  If so, this is by design

**Comment by LisaReddy** [comment]
Ok.  Once Robin okay's it, then I will close issue.
Thx

**Comment by LisaReddy** [comment]
Robin consented on abreviations/
Closing issue
