### ISSUE TITLE
Defect - No 6/8 Glossary Term

### ISSUE THREAD

**Issue by LisaReddy** [18F/State-TalentMAP#1884]
<There is no glossary term for 6/8

Steps:
1. Click on Glossary 
2. Expand 6/8
3. NA is displayed

User Story:
As a bidder, I want to find the definition for 6/8

Acceptance Criteria:
The system should provide and display a definition for 6/8
![six_eighth_glossary_term](https://user-images.githubusercontent.com/37226508/39703443-98051768-51f7-11e8-89f4-f24d4128db4c.jpg)

**Comment by burgwyn** [comment]
Looks like this was the value we loaded in.  Can we work with @BrownCA5  to update the definition? 
<img width="346" alt="screen shot 2018-05-07 at 9 09 26 am" src="https://user-images.githubusercontent.com/661204/39703577-7ad4b6a6-51d6-11e8-8aa5-f1336bd4748c.png">

**Comment by afrasier** [comment]
I've updated the DOS Dev instance with the definition sent via e-mail.
We'll want to make sure to update the CSV files with the data for future environments.

**Comment by LisaReddy** [comment]
6/8 terminology has been updated in TalentMap Glossary.
Closing issue.
