### ISSUE TITLE
Defect - Correct Back button verbiage on Compare Page

### ISSUE THREAD

**Issue by LisaReddy** [18F/State-TalentMAP#1885]
<The Back button verbiage on the Compare Page needs to be corrected :
        From: Back to to Search results
        To: Back to Search results

User Story:
As a bidder, I want to return to search page when I am on the comparison page.

Accepted Criteria:
The system should display the correct verbiage on the return function.
![back_bttn_sp_comp_page](https://user-images.githubusercontent.com/37226508/39704265-4a068800-51fa-11e8-80ed-c3a8650cbf3c.jpg)

**Comment by burgwyn** [comment]
Assigning to @Icemanbeta - please PR into `release-candidate-1`

**Comment by LisaReddy** [comment]
This is also on the Position detail page.

**Comment by mjoyce91** [comment]
@burgwyn I already have a fix, will PR.

**Comment by LisaReddy** [comment]
Corrected with new build
Closing Issue
