### ISSUE TITLE
Multiple elements in Home.jsx have same name attribute

### ISSUE THREAD

**Issue by jseppi** [18F/State-TalentMAP#205]
Multiple elements have `name="historical-figures-1"`. Probably a copy-pasta error.

See:
- https://github.com/18F/State-TalentMAP/blob/0bd2dfac166455f1347616d00bcfac75ab7ab44e/src/Containers/Home/Home.jsx#L193
- https://github.com/18F/State-TalentMAP/blob/0bd2dfac166455f1347616d00bcfac75ab7ab44e/src/Containers/Home/Home.jsx#L211
- https://github.com/18F/State-TalentMAP/blob/0bd2dfac166455f1347616d00bcfac75ab7ab44e/src/Containers/Home/Home.jsx#L260

**Comment by burgwyn** [comment]
🍝 - @mjoyce91

**Comment by burgwyn** [comment]
Closing via #207
