### ISSUE TITLE
Domestic filter

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#215]
As a bidding employee,
I want to be able to manually search positions using a domestic filter
to provide available positions that are in the US

Acceptance criteria:
- The presentation of the domestic filter is provided to the user to make their desired selection
- The default selection is null, so all positions are displayed
- When a region bureau is selected, the region bureau choice appears to remind the user of what region bureau(s) they have selected
- More than one region bureau can be selected as a filter at a time

Definition of done:
Assumptions documented
Coded work is complete
Full unit test coverage
Product owner approval

**Comment by mjoyce91** [comment]
@burgwyn - looks like the description needs to be updated on this one. Domestic vs region bureau / copy and paste.

**Comment by burgwyn** [comment]
Closing
