### ISSUE TITLE
Saved Search Filters

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#216]
As a bidding employee,
I want to be able to save a set of search parameters
So I can repeat the search for future research

Acceptance Criteria
* User needs a mechanism for saving a search
* User can custom name a search
* User will receive visual confirmation that the search has been saved
* User can save more than one search

**Comment by esgoodman** [comment]
@burgwyn @mjoyce91 @krisdelacruz I think we should deprioritize these filters given results from usability tests with bidders.

**Comment by burgwyn** [comment]
Closing
