### ISSUE TITLE
Edit a Saved Search

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#218]
As a user,
I want to edit a saved search,
So that I can save a version of a modified search

## Acceptance Criteria
* User can modify the list of saved search parameters
* User can rename the search
* User receives confirmation that the edits were saved

**Comment by esgoodman** [comment]
@burgwyn @mjoyce91 @krisdelacruz I think we should deprioritize these filters given results from usability tests with bidders.

**Comment by burgwyn** [comment]
Closing
