### ISSUE TITLE
Clone an existing saved search

### ISSUE THREAD

**Issue by BrownCA5** [18F/State-TalentMAP#220]
As a user,
I want to be able to clone an existing saved search
So that I can re-use existing search parameters when making edits for a new search. 

## Acceptance Criteria

User can clone the list of saved search parameters
User can rename the search
User receives confirmation that the edits were saved
Default name would be previous search + a number, eg "My Search 1"

**Comment by esgoodman** [comment]
@BrownCA5 @burgwyn This feature is pretty far in the future on the roadmap -- given what we're learning from research, I'd argue that all saved search implementations are less urgent than working on favoriting and automatic calculations.

**Comment by burgwyn** [comment]
Closing
