### ISSUE TITLE
Create 'No Results' Component

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#229]
For many of our list-based views there is the possibility that the list will be empty.  Create a component that displays clearly to the user that the list is empty.  The actual text should be prop.

**Comment by mjoyce91** [comment]
@burgwyn - how about using the new Alerts component to accomplish this?

**Comment by burgwyn** [comment]
I like the idea and we can try it under the guidance of the UI/UX team.

My original motivation came from the [ListActivity](https://developer.android.com/reference/android/app/ListActivity.html) in Android.  It has a pattern that allows you pair a list view with a second, "the list is empty" view.  The result is this:

```
ListView lv = (ListView)findViewById(android.R.id.list);
TextView emptyText = (TextView)findViewById(android.R.id.empty);
lv.setEmptyView(emptyText);
```

In general, list UIs that don't account for an empty state make me 😞

**Comment by krisdelacruz** [comment]
Noted: Visualization or notifications that "No results" are available. 
• Search Results Page
• Favorites page
• Home page

**Comment by mjoyce91** [comment]
@krisdelacruz - reassigning this to you.

**Comment by esgoodman** [comment]
@krisdelacruz Let's talk about moving this up in our next sync. If we are trying to wrap up a first round of search/filter stories this one is more basic and important than saved searches.

**Comment by wongperson** [comment]
@krisdelacruz @shanzasubz is this fully realized enough to close the issue or should this remain open as an issue?

**Comment by krisdelacruz** [comment]
@wongperson let's close =)
