### ISSUE TITLE
Region filter

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#23]
As a bidding employee, 
I want to be able to manually search positions using a region filter
to provide available positions that are in a certain geographic region

**Acceptance criteria:**
	- The presentation of the region filter is provided to the user to make their desired selection
	- The default selection is null, so all regions are displayed
	- The available Foreign Service regions should be presented by regional Bureau 
	- When a region is selected, the region choice appears to remind the user of what region(s) they have selected
	- More than one region can be selected as a filter at a time

**Definition of done:**
Assumptions documented
Coded work is complete
Full unit test coverage
Product owner approval

**Comment by burgwyn** [comment]
Closing
