### ISSUE TITLE
Update regex for email validation check

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#246]
Use recommendation by @jseppi to cover false positives:
`function validStateEmail(email) {
  return /.+@state.gov$/.test(email.trim());
}`

**Comment by mjoyce91** [comment]
@jseppi - looks like `boop@state.gov@state.gov` still passes against that regex. Maybe this is something we table until we have a better idea of what our designers think this interaction should look like before bringing in a new lib or spending too much time on. Also, we may determine that is handled by the API depending on mail server availability.

**Comment by jseppi** [comment]
yeah, it will, but when coupled with the `type="email"` in the `input` (#243), we should be 👍 

<img width="713" alt="screen shot 2017-07-26 at 3 40 54 pm" src="https://user-images.githubusercontent.com/697848/28642695-e297d12c-7218-11e7-8921-1cd34afee3c8.png">

**Comment by jseppi** [comment]
I also agree though it is not worth spending too much effort on for now

**Comment by mjoyce91** [comment]
Ah you're right! However, doesn't this block them from submitting the form? We don't want to block them, we just want to inform and warn them if it's an external email address.

**Comment by jseppi** [comment]
Oh yeah, it would block them. My mistake!

**Comment by mjoyce91** [comment]
Resolved in #271
