### ISSUE TITLE
Tour of duty length filter

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#25]
As a bidding employee, 
I want to be able to filter out search results of available posts based on the tour of duty
to provide posts based on the length of the potential assignment

**Acceptance criteria:**
	- The selection of the tour length filter is provided to the user to make their desired selection
	- The default selection is null, so all tour length options are displayed
	- The bidder can pick from a tour of duty length description code
	- When a tour of duty is selected, the tour of duty choice appears to remind the user of what tour length(s) have been selected
	- More than one tour of duty may be selected

**Definition of done:**
Assumptions documented
Coded work is complete
Full unit test coverage
Product owner approval

**Comment by apbdevine** [comment]
Edited story to remove Tour of Duty length based on information received from DOS team. "the standard TOD is associated with a post. We do not maintain a TOD for a position. When assignments are initiated the TOD defaults to the Post's. However, the assignment TOD can be changed by selecting from the common list of TODs or creating a customized TOD."

**Comment by burgwyn** [comment]
Closing
