### ISSUE TITLE
Add onBlur to email validation input

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#253]
In order to delay the alert from appearing, use `onBlur` with the email validation function.

**Comment by mjoyce91** [comment]
@jseppi - I agree there's probably a better way to do this, such as using `onBlur` like you mentioned. However, this is a situation I can arising where we'd want that immediate visual feedback: http://g.recordit.co/dH7MHpiT4W.gif

**Comment by jseppi** [comment]
Hrmmmm.... maybe we should let the design and user research shake out a bit more before getting any fancier with this. I have a feeling the interaction is likely going to change when sharing with an internal vs external user.

**Comment by mjoyce91** [comment]
Will wait to see how designers implement this feature
