### ISSUE TITLE
Danger pay filter option

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#26]
As a bidding employee, 
I want to be able to add search criteria to include positions with danger pay
for opportunities with danger pay in my results list

**Acceptance criteria:**
	- The bidder is able to indicate if they would like to include danger pay opportunities
	- By default, danger pay opportunities are included in the positions results list
	- The bidder must be able to read text content that asks if the bidder would like to include danger pay opportunities (or some form of instruction)
	- When indicated, the search includes a danger pay filter

**Definition of done:**
Assumptions documented
Coded work is complete
Full unit test coverage
Product owner approval

**Comment by afrasier** [comment]
@mjoyce91 `/api/v1/positions/post__danger_pay__gt=0` will return positions with only posts having danger pay > 0

**Comment by burgwyn** [comment]
Closing
