### ISSUE TITLE
Execute search

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#27]
As a bidding employee, 
I want a way to execute a search against available positions based on selected filters
So that I can see the opportunities that match my search parameters

**Acceptance criteria:**
The bidder must be able to execute the search
The bidder will be provided a listing of the search results
The bidder must select at least two filters
The bidder should receive an indication if they failed to enter at least two filters and the search will not execute

**Definition of done:**
Assumptions documented
Coded work is complete
Full unit test coverage
Product owner approval

**Comment by wongperson** [comment]
Assumption: all positions provided in dummy data are available for sprint.  

FOLLOW-UP: Must define what "available" positions means

**Comment by mjoyce91** [comment]
How are we defining two filters? For example, if the user chooses two languages, does this meet the requirement? Or would the user need to choose from another filter set, such as grade, in order to meet the requirement? Does search bar text count as one of these two?
