### ISSUE TITLE
Capsule Descriptions for Positions

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#281]
As a Bidder,
I would like a brief description of a position
So that I can understand the basic roles and responsibilities of that position

## Acceptance Criteria
- Text is supplied by the bureau/post
- Text is searchable

**Comment by BrownCA5** [comment]
What do you mean by viewing one position, and not two positions in one description?

**Comment by wongperson** [comment]
@BrownCA5 @afrasier We will need to determine what central system contains capsule descriptions to pull from, unless TalentMAP owns the SoR and content management for capsule descriptions going forward.

**Comment by BrownCA5** [comment]
@wongperson Capsule descriptions are text entered into FSBid.  There is no other SoR that maintains them.  So there is no where to pull capsule descriptions from since they only reside in FSBid.

**Comment by afrasier** [comment]
Right, Pat sent me a set of capsule descriptions exported from FSBid that we can use for now. I think the content management issue is going to be something we'll need to address in the future for sure though.

**Comment by krisdelacruz** [comment]
Are we able to view those capsule descriptions on the API when they are implemented @afrasier so we can implement on the wireframes?

**Comment by afrasier** [comment]
Yeah, they'll just be another text field, although fairly long. (Max 2000 characters)

**Comment by wongperson** [comment]
@esgoodman, since the original story was developed and completed, not sure I understand why this is still outstanding.  With your concurrence, I will close this and allow @krisdelacruz to open any related issues as necessary.

**Comment by krisdelacruz** [comment]
@wongperson noted! Thank you!

**Comment by wongperson** [comment]
I don't have a record of a front-end for this interface anywhere, this may need to become a new story for front-end capsule description management.

**Comment by esgoodman** [comment]
@wongperson Agreed. This is actually a pretty big lift, because it involves creating a front end to input and update the stored text fields. For the sanity of @krisdelacruz and myself, I'd recommend closing this one and opening a new epic focused on _capsulte description management_ functionality from the perspective of the bureau: 

As an authorized editor within a bureau
I need a way to manage position descriptions
So that I can keep them up-to-date and accurate

Or something like that.

**Comment by mjoyce91** [comment]
Editing capsule descriptions was completed via #532 and #720

**Comment by mjoyce91** [comment]
Completed
