### ISSUE TITLE
Clear search filters

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#29]
As a bidding employee,
I want to set all of my search filter criteria to their default selection
So I can start my search process over with a new combination of search criteria

**Acceptance criteria:**
- The bidder should no longer see search results
- The bidder should be returned to the search filters/parameters default view
- The bidder should see that all selections for their search filters are reset to their default selections
- The bidder should receive a prompt before clearing search filters

**Definition of done:**
Assumptions documented
Coded work is complete
Full unit test coverage
Product owner approval

**Comment by burgwyn** [comment]
Closing
