### ISSUE TITLE
Position description

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#30]
As a bidding employee,
I want to be able to see expanded details about the position
So I can further understand whether the position matches my professional preferences

**Acceptance criteria:**

- Upon selecting the position from the search results, the bidder should be able to see the written description and requirements of the position
- The bidder should be able to see post and position information, including:
    - Skill code
    - Danger pay
    - Language requirements
    - Position grade
    - Region
    - Post
    - Post differential
    

**Definition of done:**
Assumptions documented
Coded work is complete
Full unit test coverage
Product owner approval

**Comment by apbdevine** [comment]
Edited acceptance criteria to remove Tour of Duty length based on information received from DOS team. "the standard TOD is associated with a post. We do not maintain a TOD for a position. When assignments are initiated the TOD defaults to the Post's. However, the assignment TOD can be changed by selecting from the common list of TODs or creating a customized TOD."

**Comment by mjoyce91** [comment]
Using placeholder data for **Region**.
