### ISSUE TITLE
Create Content Security Policy

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#302]
Recommend and implement a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) to ensure only content from same origin and trusted domains is supported.

**Comment by jseppi** [comment]
Just FYI on this one: New Relic's browser monitoring instrumentation will [not work with CSP](https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-new-relic-browser#csp). As far as I know there aren't any plans to include New Relic, but just wanted to flag in case.

**Comment by jesse-russell** [comment]
So just to flesh out this issue a bit more, my understanding is that we want to accept content from ourselves as well as a few specific trusted domains. I will add to this that we should enforce SSL for any resources loaded from domains outside of our own. 

Although support for CSP in Internet Explorer appears to be limited, my initial thoughts would be to include a policy similar to the following:
`Content-Security-Policy: default-src ‘self’ https://*.trustedsite.com https://trustedsite.com`
Where trustedsite.com is replaced by vetted content providers the UI wants to pull resources from.

Additionally, I'm curious to hear other people's thoughts on whether we should look at adding an API endpoint for CSP violation reporting?

**Comment by burgwyn** [comment]
@jesse-russell - are you thinking something like this?
```
Content-Security-Policy: default-src 'self'; report-uri http://reportcollector.example.com/collector.cgi
```
I can look into incorporating it into a future version of the Node app

**Comment by jesse-russell** [comment]
@burgwyn You got it. It might be worth throwing in the backlog for later consideration.

**Comment by burgwyn** [comment]
I added a version of this to our dev server.  The result was this:

<img width="1397" alt="screen shot 2017-08-18 at 5 44 11 pm" src="https://user-images.githubusercontent.com/661204/29479077-2da4b162-843e-11e7-9fa8-345038e984b0.png">

Because we're making AJAX calls I added a value for `connect-src`.  The result was this (which is what we want):

<img width="1392" alt="screen shot 2017-08-18 at 5 51 24 pm" src="https://user-images.githubusercontent.com/661204/29479221-f003be88-843e-11e7-9054-57db784c7857.png">

**Comment by burgwyn** [comment]
End result:

```
Content-Security-Policy: default-src 'self'; connect-src *.domain.tld;
```

Created #395 to support the `report-uri` idea
