### ISSUE TITLE
Post differential filter

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#31]
As a bidding employee,
I want to be able to add search criteria to include positions with post differential
for opportunities with post differential pay in my results list

Acceptance criteria:
- The bidder is able to indicate if they would like to include post differential pay opportunities
- By default, post differential pay opportunities are included in the positions results list
- The bidder must be able to read text content that asks if the bidder would like to include post differential pay (or some form of instruction)
- When indicated, the search includes a post differential pay filter

Definition of done:
Assumptions documented
Coded work is complete
Full unit test coverage
Product owner approval

**Comment by afrasier** [comment]
@mjoyce91 `/api/v1/positions/post__differential_rate__gt=0` will return positions with only posts having differential rate > 0

**Comment by esgoodman** [comment]
@burgwyn @mjoyce91 @krisdelacruz I think we should deprioritize these filters given results from usability tests with bidders.

**Comment by burgwyn** [comment]
Closing
