### ISSUE TITLE
Credentials for public users

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#315]
Now that we have a public URL and login implemented, we should consider ways to enable users to be able to access the prototype either without logging in, or with credentials provided to them. Otherwise, any one wishing to use the prototype would be blocked by the login page.

@burgwyn

**Comment by burgwyn** [comment]
Good idea.  We can use the personas the @krisdelacruz and @shanzasubz created and add them to our deployment scripts.

**Comment by burgwyn** [comment]
Pre-populate the login screen with valid persona credentials to enable the public to login
