### ISSUE TITLE
Move login Alert status above the login form instead of below

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#329]
The Alert notifying the user of their login status (logging in, error, etc.) should be placed above the login form instead of below it.

**Comment by mjoyce91** [comment]
@burgwyn - http://recordit.co/7JkgLicShd - this feels a little awkward, so without spending too much time trying to re-style this page our own, I think it makes more sense to wait for designs from Kristian and Shanza. Could set a min-height above the form, but then there's a lot of white space.

**Comment by burgwyn** [comment]
Is the concern reserving space for the Alert?

**Comment by mjoyce91** [comment]
Right - if you don't, then the login form drops down as soon as the alert appears. If you do, then you have a ton of white space above the form when the alert isn't present.

**Comment by burgwyn** [comment]
Let's hold tight and wait for designs
