### ISSUE TITLE
Capsule Descriptions for Positions - Content Management

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#352]
As a sufficiently authorized user,
I want to create, edit and delete a capsule description,
So that I can provide a description of the roles and responsibilities of a position

## Acceptance Criteria
- User must be logged in
- An endpoint(s) to create/edit/delete capsule descriptions
- Capsule descriptions are full-text searchable
- Additional metadata is captured
  - When the create/edit/delete took place
  - Who made the last edit

**Comment by esgoodman** [comment]
@afrasier Two questions --

1) can we close this one? or does it require more action? 
2) where is the documentation about what constitutes a sufficiently authorized user? want to make sure that's memorialized somewhere for later training.

**Comment by afrasier** [comment]
Yeah this is done. A sufficiently authorized user is one who has the permission `post_editor_X` where x is the post's ID
