### ISSUE TITLE
Integrate Node.js/Express app with front-end

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#356]
Create a basic node.js/express application to exist between Apache and the React application, to serve as a real router. For eventual integration with React server side rendering.

**Comment by jseppi** [comment]
Where are we prioritizing this one? Should be a fairly light lift, and it will be nice to have so we can easily pass around links to app routes.

**Comment by jseppi** [comment]
I think this is probably something that should be in the Release Candidate, and I've tagged it as such. We will want folks to be able to deep-link to position details, for instance, without having to manually traverse.

**Comment by burgwyn** [comment]
@jseppi I feel like we may have covered this in #1454

**Comment by jseppi** [comment]
Yep, confirmed this works great in the `dev` branch. Thanks!
