### ISSUE TITLE
Reconcile zero-based Pagination component and one-based API pagination

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#385]
Because the `ReactPaginate` module is zero-based, it expects the first page of results to be `0`, whereas the API expects the first page to be `?page=1`. Because of this, there are some messy prop definitions, such as `defaultPageNumber={this.state.defaultPageNumber.value - 1}` in `Results.jsx`. A clean solution should be created to reconcile the difference between the module and the API, while maintaining readability and consistency.

**Comment by BrownCA5** [comment]
Need associated milestone added.
