### ISSUE TITLE
Obtain the DoS style guide

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#4]
As a visual designer, I would like to understand the existing DoS guidelines for color palettes, logos & images, typography schemes, and written content in order to build a design for the TalentMAP product.

**Comment by apbdevine** [comment]
As of 6/7 meeting (per Prasanna) DOS does not currently have an official style guide, therefore they are compiling and will send once approval is complete.

**Comment by apbdevine** [comment]
As of 6/27 received files from Prasanna/DOS; Booz Allen team needs to review
