### ISSUE TITLE
Work with Design Team to Determine Mobile Responsive Account Dropdown

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#406]
Based on feedback in #392, the Account dropdown does not work with the mobile responsive nav. When mobile responsive nav is visible, clicking on the Account Dropdown results in the entire nav menu closing. It is unlikely that the Account Dropdown will be used in mobile nav (since it requires multiple clicks), but we should still confirm with the Design team as to how this will look.

![responsive-account-menu-bug](https://user-images.githubusercontent.com/697848/29527026-2228a2aa-865d-11e7-8eab-a9be31c579d8.gif)

https://github.com/18F/State-TalentMAP/pull/392/files/45207f3cb64e7d72eb301c46108db320cdc0593b#diff-fb00150605115caa3d3fe1f2f46b1fb3

**Comment by mjoyce91** [comment]
@krisdelacruz @shanzasubz - any thoughts?

**Comment by mjoyce91** [comment]
Here's a possibility:

![48wbyjxgo8](https://user-images.githubusercontent.com/11576347/29538063-1179b180-8692-11e7-8121-72d60f51d591.gif)

**Comment by krisdelacruz** [comment]
@mjoyce91 @burgwyn I would choose the second version you have shown above (with the navigation items all shown). This will be a separate story on our end to show all the responsive views for MVP.
