### ISSUE TITLE
Notify employees when saved searches yield updated results

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#412]
As a user, 
I want to be notified if my saved searches yield new or different results from the last time I viewed results with that search criteria, 
so that I can be aware of new or updated position postings based on my saved search criteria preferences.

Example from USAJOBS:

<img width="1096" alt="screen shot 2017-08-22 at 9 29 19 am" src="https://user-images.githubusercontent.com/11576347/29567859-74c93604-871c-11e7-9cce-2d2d69f1229b.png">

## Acceptance criteria
- A job that runs when new positions are added, edited, or deleted
- Job runs the saved searched against all positions
- A notification indicating a change in the number of results on a saved search
- A flag on the save search object to store the user's preference on notifications

**Comment by burgwyn** [comment]
Closing
