### ISSUE TITLE
API - Favoriting Positions

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#438]
As a bidder,
I want to save my favorite positions on my profile
So that I can save my favorite positions across browsing sessions

## Acceptance criteria
- Ability to save favorite from front end via API

**Comment by afrasier** [comment]
Is this favoriting things _other_ than positions? Favoriting positions is already supported on the API.

**Comment by burgwyn** [comment]
@afrasier - thanks.  Let me rewrite for frontend

**Comment by afrasier** [comment]
Right now it's supported via PATCHing the user's profile, but I can add a nicer endpoint of `/api/v1/position/{id}/favorite/` if you think it's worthwhile
