### ISSUE TITLE
Wireframe Add To/Remove From Draft Bid List

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#441]
As a bidder,
I want to add/remove positions in a draft "bid list"
So that I can keep track of my positions in my profile

## Acceptance criteria
- Bidders are limited to a maximum of 10 bids
- Create user flows on where to "Add to Bid List"
- Wireframe view of Bid List
- Activity around removing a position

**Comment by burgwyn** [comment]
Closing
