### ISSUE TITLE
Homepage Map 

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#460]
As a bidder,
I want a clear visual of a map
So that when I hover over specific regions I can get search results of the positions in that region

## Acceptance criteria
- Geolocation of the 7 regions
- A wireframe representation of the position search view
- Applies the design created by the design team
- Applies the US Web Design Standards

### Resources
- State Department style guide

**Comment by esgoodman** [comment]
Our current design does not use the map #1168.
