### ISSUE TITLE
Add conditional coloring for header links

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#480]

**Comment by mjoyce91** [comment]
@krisdelacruz - would you be able to explain the interaction with the search bar? Does the search bar only appear if you click the "Search" button in the header? If so, how would the conditional coloring for the header links work?

**Comment by mjoyce91** [comment]
We also don't have full-fledged links in the nav (two of them just direct to Github), so this can probably wait.

**Comment by burgwyn** [comment]
Removing milestone
