### ISSUE TITLE
Add CSS rules to capitalize section titles, instead of manually entering capitalized text

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#487]
Occurs in the search results cards and position details section titles.

**Comment by burgwyn** [comment]
Do we want `uppercase` or just `capitalize`?

**Comment by mjoyce91** [comment]
Forgot that `capitalize` is also a rule. We should use `uppercase`.

ex: "An example Title" => "AN EXAMPLE TITLE"
