### ISSUE TITLE
Header - US flag image does not display

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#492]
The header image, a US flag, is not displaying:

<img width="483" alt="screen shot 2017-09-07 at 9 27 25 am" src="https://user-images.githubusercontent.com/661204/30165746-202475f6-93af-11e7-8413-d2f5f7ead050.png">

It appears as though our Content Security Policy is partly at fault:

<img width="1386" alt="screen shot 2017-09-07 at 9 27 50 am" src="https://user-images.githubusercontent.com/661204/30165747-20272aa8-93af-11e7-8245-f33877788d9a.png">

**Comment by mjoyce91** [comment]
This is weird though, because that image is referenced internally, which we do elsewhere.

**Comment by burgwyn** [comment]
I think part of the fix may be to move away from our approach of

```
import image from '/images/image.png';
```

This will be especially important as we look to build out an Express application.

**Comment by burgwyn** [comment]
Resolution was to update the Content Security Policy to include:

```
img-src 'self' data: https:;
```
