### ISSUE TITLE
Submit Bid List

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#535]
As a bidder
I need a means to submit my bid list
So that I can confirm interest in a position

## Acceptance Criteria
- A means for a bidder to submit their final bid to TalentMAP for review
- A confirmation of submission
- Ensure a minimum of 1 bid and parameter maximum of bids are submitted

**Comment by wongperson** [comment]
It would be possible to do rolling submissions in addition to bulk submission.
