### ISSUE TITLE
UI - Bidder View - Handshake Indicator

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#538]
As a bidder,
I want to see an indication that I have a handshake for a position
So that I can manage my ultimate position choices

## Acceptance Criteria
- A view of submitted positions
  - Indicator for summary data for bidders
    - Number of bids
    - Number at grade of position
    - Number in skill code
  - Indicator that a position has a handshake
  - Indicator that the recipient of the handshake is the currently logged in bidder
- Indicator appears in position details

**Comment by wongperson** [comment]
@burgwyn considering this is now in the bid tracker, should we deem this feature closed?

**Comment by burgwyn** [comment]
I think so
