### ISSUE TITLE
New and Popular Positions title underline offset

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#578]
The text being underlined is slightly offset from the main gray underline.

**Comment by jseppi** [comment]
I'm no CSS Whiz, but getting this pixel-perfect might be kinda tricky.

**Comment by mjoyce91** [comment]
If we keep it static (not dynamic based on length of text) it may be simpler.

**Comment by mjoyce91** [comment]
<img width="1398" alt="screen shot 2017-09-19 at 11 03 55 am" src="https://user-images.githubusercontent.com/11576347/30599405-589ce9ca-9d2a-11e7-93f1-d30bc85312a0.png">

🙌🏻
