### ISSUE TITLE
Identify and schedule user research interviewees

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#6]
Work with the Department of State to identify enough candidates to interview for TalentMAP research, (approximately 15-20 interviewees) across the following user types:

- Bidders
- Career Development Officers
- Assignment Officers

**Comment by krisdelacruz** [comment]
Currently on progress to identify volunteers for "Bidder" users as of June 8, 2017. Created an Interview List spreadsheet to keep track of volunteers.
