### ISSUE TITLE
Unmoderated test of search / filter navigation with likely users

### ISSUE THREAD

**Issue by esgoodman** [18F/State-TalentMAP#607]
### Story
As a designer of TalentMap, 
I need more information about what kinds of information are most important to bidders
So that I can revise the home page 

*Background* We have just put together our initial landing page and search filters, and we haven't done any testing. As a way to both do testing and build more engagement with a group of volunteer testers from State, we will send out a quick interactive survey.

### Questions to answer
1. How much of a priority should geospatial search be on the home page? 
2. Which types of search filters are most useful on the side nav?
3. Are there are any necessary types of information we're missing?

### Methods
We're going to conduct a ["first click" exercise](https://www.optimalworkshop.com/chalkmark) combined with a quick survey sent to the list of State employees we have who are interested in participating. 

### Goals

This will not get us very deep or rich answers, but will give us some quick feedback on pressing questions from a wider array of State employees than we could feasibly interview in the same timeframe. We can use the data to target more thorough usability tests in a next sprint. 

### Steps
- [x] @krisdelacruz writes questions and socializes with team to make sure we're hitting the key topics 
- [x] @krisdelacruz puts together screenshots of current wireframes
- [x] @esgoodman loads materials into Optimize Workshop using GSA account
- [x] @esgoodman and @krisdelacruz write up email blurb for respondents
- [x] Robin sends email with link to survey to employees' list

### Acceptance criteria
* Results pulled from [Optimal Workshop](optimalworkshop.com)

**Comment by krisdelacruz** [comment]
@BrownCA5 Will need to coordinate a time to go over the ChalkMark and get feedback on the tasks.
