### ISSUE TITLE
UI - Submit Bid List

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#634]
As a bidder
I need a means to submit my bid list
So that I can confirm interest in a position

## Acceptance Criteria
- A mechanism for adding a single position to the bid list
- A mechanism for removing a single position from the bid list
- A view that displays all current positions on the bid list
- A means for a bidder to submit their final bid to TalentMAP for review
- A confirmation of submission
- Ensure a minimum of 1 bid and parameter maximum of bids are submitted

**Comment by mjoyce91** [comment]
@afrasier - I'm guessing the API will check that the Bid List meets the parameter minimum/maximum upon attempted submission, correct?

**Comment by afrasier** [comment]
Yeah, I'm thinking we'll hardcode that number for now and when we get a story to allow for changing it I'll factor it out into something the front end could alter.

Basically, you'll call something like PUT `/api/v1/bidlist/position/{id}/` to add a position to a bidlist, then you'll call `/api/v1/bidlist/submit/` to submit the current contents of the bidlist. You can add extra bids to the list after the submission, but they won't be marked as submitted unless you submit the list again. (Submitting will be an idempotent process, so it won't affect previously submitted bids)
