### ISSUE TITLE
Language waiver tracking

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#647]
### Story
As a language SME/CDO,
I want to track when and where a language waiver was requested and/or granted,
So that I can analyze language requests at the position and bidder/assignee levels.

### Acceptance criteria
* a way to designate a bidder/assignee as having requested/receiving a waiver
* a way to see partial and full language waivers requested and granted to a position
* a way to track the partial and full language waiver history of a bidder/assignee
* a way to track the waiver request history by language

### Notes
* waivers are for the person, not the position

**Comment by wongperson** [comment]
@BrownCA5 take a look at this idea prior to grooming.

**Comment by BrownCA5** [comment]
@wongperson - this one is very good as well.

**Comment by burgwyn** [comment]
Closing
