### ISSUE TITLE
Position/Employee Curtailment

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#648]
### Story
As a CDO,
I want to know why an assignee curtailed their tour of duty (left position early),
So that I can determine if this is a problem with the position, post, or employee

### Acceptance criteria
* A way to view a bidder or assignee's history of curtailment
* A way to view a position's history of curtailment
* A way to select generic reason codes for why an employee left a position
   * Values: medical, security clearance, service need, compassionate, other

### Notes
* Curtailment resides with the person

**Comment by wongperson** [comment]
@BrownCA5, here's another one from the 9/22 brainstorming - take a look.

**Comment by BrownCA5** [comment]
@wongperson - I like it; well written.

**Comment by burgwyn** [comment]
Closing
