### ISSUE TITLE
Bid Removal Restriction

### ISSUE THREAD

**Issue by BrownCA5** [18F/State-TalentMAP#663]
As a CDO
I need to ensure that once a bid is placed on a position the bid cannot be removed by the bidder after the bidding deadline closes
So that I can ensure the integrity of the bid

 ## Acceptance Criteria
* The CDO should have an override ability to remove the bid after the bid cycle closes
* The bidder is notified that the removal has been processed

**Comment by burgwyn** [comment]
Closing
