### ISSUE TITLE
Test functions by simulating actions instead of calling strictly on the component instance

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#709]
For some tests, functions are only tested at the Component level, instead of testing that the associated action related to the function also works. For example, a function `someFunction` might be fully tested, but the related `<button onClick={this.someFunction} />` should also be tested using `simulate`/`click`.

**Comment by burgwyn** [comment]
I agree with the strategy though the scope is fairly broad.  I'll start with `<button />` for now.
