### ISSUE TITLE
Use more descriptive parameter name for "e"

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#712]
`e` is often used as the parameter name when accessing the object passed by a text input, such as `{ target: { value: ... } }`. Use a more descriptive parameter name.

**Comment by mjoyce91** [comment]
@burgwyn - I'll pass this one off to you if you have time to look at it over the next week. If not, I'll pick it back up.

**Comment by burgwyn** [comment]
Closing
