### ISSUE TITLE
See Projected Vacancy

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#747]
### Story
As a bidder,
I want to make sure I am able to view the Projected Vacancy,
So that I can predict the next move in the bidding process.

### Acceptance criteria
* When researching a position, I can see the projected vacancy date
* After a position is filled, a new projected vacancy is populated and visible

**Comment by esgoodman** [comment]
This seems like more of a CDO story, @wongperson -- seems like the key thing for bidders is just whether this position is open for this bidding cycle or not?

**Comment by burgwyn** [comment]
Duplicate of #758
