### ISSUE TITLE
Spousal/EFM Employment Information/Opportunities

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#748]
### Story
As a bidder,
I want to be able to get information about Spousal Employment,
So that my spouse is able to work in the post.

### Acceptance criteria
* When researching a position, I can see information about Eligible Family Member (EFM) opportunities at the post
* Utilize OBC's FEMR???

**Comment by burgwyn** [comment]
OBC is the SME for this data and the dataset is not readily accessible.

**Comment by burgwyn** [comment]
Closing as this is out of scope for the MVP
