### ISSUE TITLE
Panel Action Confirmation

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#751]
### Story
As a bidder,
I want to get a notification when I am confirmed/assigned to the position (after the successful panel),
So that I am aware of the next steps beyond the bidding process.

### Acceptance criteria
* Bidder can see that their assignment is confirmed (i.e., approved by panel)
* The bidding process is considered complete for the bidder and the position is represented as such

**Comment by burgwyn** [comment]
Closing
