### ISSUE TITLE
Bid Tracker

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#752]
### Story
As a bidder,
I want to know the status of my bid,
So that I know where I am in the bidding process.

### Acceptance criteria
* The bidder can see where their submitted bids are in the process of consideration
* Shows up in the bidder's dashboard

**Comment by mjoyce91** [comment]
Possible module to use - https://github.com/mu29/react-stepper

**Comment by krisdelacruz** [comment]
12.8.17 Wireframe session

https://projects.invisionapp.com/freehand/document/TKjKGOQX

## Next steps
- Make edits on the Bid Tracker workflow 
- Make edits on bid tracker sketches
- Communicate with @mjoyce91 on next steps on development

**Comment by krisdelacruz** [comment]
Presented Mocks up of Bid Tracker for everyone references. Will continue test and iteration.

[BidTracker_Mockups_Dev_v1_small.pdf](https://github.com/18F/State-TalentMAP/files/1561034/BidTracker_Mockups_Dev_v1_small.pdf)

**Comment by krisdelacruz** [comment]
**# #InVision Prototype**

InVision Prototype: https://invis.io/SZEYMMDU8
