### ISSUE TITLE
Count of the bids on a position

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#753]
### Story
As a bidder,
I want a count of the latest current bids on a position,
so that I am able to see bid statistics of others who bid on this position

### Acceptance criteria
* An accurate count of total bids on a position visible to the bidder on the position details page
* The same count of total bids on the position search results view, favorites view and bid list
* Count includes only bids with a state of submitted or greater

**Comment by esgoodman** [comment]
Again, I think we can descope this a bit if we need to. It adds complexity to the UI that we'll probably want to test. Start with total number of bids and then gradually add enhancements. That's my proposal.

**Comment by burgwyn** [comment]
Closing
