### ISSUE TITLE
Search Filters - Incorporate non-regional burueas

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#785]

**Comment by afrasier** [comment]
This query will list all bureaus, sorted by regional flag and then by short_description

`/api/v1/organization/?ordering=-is_regional,short_description&is_bureau=true`

**Comment by esgoodman** [comment]
@afrasier is this implemented?

**Comment by afrasier** [comment]
Yes, you can just filter on the regional flag. `api/v1/organization/?is_regional=false`

**Comment by esgoodman** [comment]
Closing!
