### ISSUE TITLE
Projected Vacancy Filters

### ISSUE THREAD

**Issue by burgwyn** [18F/State-TalentMAP#786]
As a bidder
I want to be able to search and filter on projected vacancies
So that I can search for future positions

## Acceptance Criteria
* Backend support for filters
* UI - add to navigation

**Comment by esgoodman** [comment]
Note that research suggests we might want to call this "start date"

**Comment by krisdelacruz** [comment]
@esgoodman Lets discuss this. This functionality is similar to FSBID where users are able to see a two-year projection of "potential' positions. I believe the only frustration is accuracy. This feature is heavily used for Tandem bidders.

**Comment by esgoodman** [comment]
@krisdelacruz this is different from transfer eligibility date, correct?

**Comment by krisdelacruz** [comment]
@esgoodman this is somewhat of a gray area from Transfer Eligibility Date (this is tied to the incumbent). From the user research, this is an actual functionality on FSBID where users can see two years ahead of time, but it is almost a forecast view— that job might not be there on actual bidding season

**Comment by burgwyn** [comment]
Closing, see #1463 for UI
