### ISSUE TITLE
Moderated Usability Testing on Homepage Designs

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#796]
### Story
As a member of the TalentMAP team
I need to have real bidders try out the homepage designs
So that we can get an understanding of what users are experiencing

### Acceptance criteria
* Need to clients involved in the process
* Create Test Script
* Test question about search
* Test question about map
* Test question about "Highlight Positions" and "new positions"

**Comment by esgoodman** [comment]
Closed.
