### ISSUE TITLE
Onboarding to DoS physical site

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#8]
Work with DoS to obtain onboarding (network/site) permissions for the vendor team.

**Comment by apbdevine** [comment]
Update as of 6/6: GSA Contracting to file a DD254 with DOS.

**Comment by apbdevine** [comment]
Working with Alexandra Scholl-Marvel within DOS to obtain badges while DD254 is being filed.

**Comment by apbdevine** [comment]
Update as of 6/26 provided DOS Booz Allen team PII information
