### ISSUE TITLE
Mission/Country Filter Wireframe

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#836]
As a Designer
I want a wireframe of the Mission/Country filter
so that the TalentMAP front-end developer is able to prototype the first view

## Acceptance Criteria
* Smart Search for users to search for Mission/Country with auto complete
* User is presented with the first 7 Missions

## User Research
* Continued Research on Mission filters
* Phase 2 testing will help validate this filter

## Method
* Card sorting on TreeJack

**Comment by esgoodman** [comment]
@krisdelacruz I think we need to think more about this in light of our first round of search/filter research with bidders. How do we help people search on location?

**Comment by krisdelacruz** [comment]
@esgoodman Agreed. I did go over Phase 2 on our next round of testing to Chris and Robin and the card sorting of Search/FIlters will be our next round.

**Comment by esgoodman** [comment]
This has been implemented.
