### ISSUE TITLE
Waiver history view

### ISSUE THREAD

**Issue by wongperson** [18F/State-TalentMAP#883]
As a CDO, 
I want the system to show me a bidder's waiver request history (e.g., language or 6/8)
so that I can better advise a bidder 

## Acceptance Criteria
- Display all language waivers for a bidder
- Display all language waivers for a position

**Comment by mjoyce91** [comment]
May have to add a story to add waiver workflow.

**Comment by krisdelacruz** [comment]
CDO opens Dashboard --> see's Jenny's Profile --> will need to click on Jenny's profile --> See Wavier History

**Comment by krisdelacruz** [comment]
Ideate on Bidder Wavier History

**Comment by mjoyce91** [comment]
@krisdelacruz - do you think this will be a new section in the user dashboard?

**Comment by krisdelacruz** [comment]
Yes @mjoyce91 this will be a new feature on the Bidder dashboard and CDO dashboard. But since this is a CDO story lets stick to the CDO
