### ISSUE TITLE
Use consistent date pattern on Profile Dashboard

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#928]
Dates should be in a consistent format, such as "8.10.17".

**Comment by mjoyce91** [comment]
@jseppi - I think what we'll do here is determine what date pattern is preferred by State, and once know that, either write a custom function, or bring in Moment.js to convert dates to `M.DD.YYYY`.

**Comment by jseppi** [comment]
👍 sounds good! Also perhaps consider a slimmer lib like [date-fns](https://date-fns.org/) because moment is pretty huge.

**Comment by mjoyce91** [comment]
I like that date-fns has a `[distanceInWords](https://date-fns.org/v1.29.0/docs/distanceInWords)` function - I'll add that in for the notifications.

**Comment by burgwyn** [comment]
Closing
