### ISSUE TITLE
Call out static data on the UI

### ISSUE THREAD

**Issue by mjoyce91** [18F/State-TalentMAP#943]
For any data that is static, add either a visual or in-line (code) indicator that the element is static and not based on any data from the API.

@jseppi any thoughts on the best way to do this?

**Comment by jseppi** [comment]
Maybe overkill, but what about:

1. Add a new boolean state variable, like `showDevContentMarker`, to control displaying a red box or something around static dev content.
1. Add a button in the UI, or maybe expose a global function that can be called in the Browser's dev console, to trigger an action that toggles the state variable?

**Comment by burgwyn** [comment]
I was thinking a dummy class name, like "static" and then adding values to the class when necessary.

**Comment by jseppi** [comment]
You could even have a component that's hooked up to state and just use it everywhere you need to put placeholder content

```jsx
const StaticDevContent = ({ isShown, children }) => {
  const style = isShown ? {display: 'inline-block'; border: '1px solid red'; } : {};
  return (<span style={style} class="static-dev-content">
    { children }
  </span>);
}

export default mapStateToProps(({ showDevContentMarker}) => isShown = showDevContentMarker)(StaticDevContent);
```

wrote that real quick on the fly, probably not totally correct, but hopefully explanatory enough :)

**Comment by mjoyce91** [comment]
That helped - here's what I put together:

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import { connect } from 'react-redux';

const StaticDevContent = ({ children, showStaticContent }) => (
  showStaticContent ?
    <div style={{ boxShadow: '0px 0px 0px 2px red' }}>
      { children }
    </div>
    :
    children
);

StaticDevContent.propTypes = {
  children: PropTypes.node.isRequired,
  showStaticContent: PropTypes.bool,
};

StaticDevContent.defaultProps = {
  showStaticContent: PropTypes.bool,
};

const mapStateToProps = state => ({
  showStaticContent: state.shouldShowStaticContent,
});

export default connect(mapStateToProps)(StaticDevContent);
```

![highlight](https://user-images.githubusercontent.com/11576347/32839193-a0d1e130-c9e1-11e7-851c-70bfc1f59318.gif)

**Comment by jseppi** [comment]
Nice!
