### ISSUE TITLE
Homepage - Skill Code

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#993]
As a Bidder
I want to search my skill code on the Homepage
so that I can focus within my cone.

## Acceptance Criteria
* Visualization of skill code selection after login as a pre-defined entry to search

## Findings
Research participants wanted to search by their specific skill code

## Recommendation
Enable to search by career track (skill cone or skill code)

**Comment by wongperson** [comment]
@burgwyn @mjoyce91 Possible resolution by rerouting of specific users to search results or a preliminary search page with filters?

**Comment by mjoyce91** [comment]
I can see something like that working. Maybe a boolean filter that's automatically selected and filters by "positions in my cone".

**Comment by mjoyce91** [comment]
Will discuss during 12/12/17 ideation.

**Comment by krisdelacruz** [comment]
Ideation Session

<img width="1283" alt="screen shot 2017-12-12 at 4 05 43 pm" src="https://user-images.githubusercontent.com/16211502/33911102-2f94506e-df5f-11e7-9c6b-3a62a3b9cd7e.png">
<img width="1012" alt="screen shot 2017-12-12 at 4 06 03 pm" src="https://user-images.githubusercontent.com/16211502/33911103-2fb651aa-df5f-11e7-81d6-52059f258c7b.png">
