### ISSUE TITLE
Search by Position title or Descriptions

### ISSUE THREAD

**Issue by krisdelacruz** [18F/State-TalentMAP#995]
As a Bidder
I want the Search Bar (keyword search) to search by position title or descriptions
so that I can efficiently search for positions 

## Acceptance Criteria
* Autocomplete feature

## Findings
Depending on their skill code users wanted to search on their specific skill code

## Recommendation
Enable to search by career track (skill code or skill code)

**Comment by wongperson** [comment]
Closed, since this is already resolved in PostgreSQL search.
